language: node_js
node_js:
  - 4.4.4
before_script:
  - chmod +x ./scripts/deploy.sh
  - openssl aes-256-cbc -K $encrypted_64697aecf649_key -iv $encrypted_64697aecf649_iv -in deployment_key.enc -out deployment_key -d
script:
  # Build the site
  - gulp build
after_success: npm run-script deploy
env:
  global:
  - secure: asI6pEzNLvQUTb8EzQ78x5tMAGKLV3mAFMnu3LOVGjKipabetymktXhfESxhCv8FekgvqLcS0R3hxuixmD/oWnTkr7t3iUxOkpg300Xo0dRawEz/2/ohL+T1f75XNCiq8dKrD6cpvVRVHwwUJ6aBNArGYehKtJfowbEGOpX0ZYL8+luLzrdenn5z0S4zZGr5TxDPTJlaQPEP8v8/H+Zc36O56tbzziVwZ6vmhhQLps2FnCEBKpFoSaumCvC39lQ5+3xgb3LH/2kyfBnM6eveABrba6Ir+Qxw7yPrMMGaQ3yaR4EOQvziW9QmolBuwTw9XaaGEvhjByXOR+gtGx7xEQb4rUN/SrmGOtigfADsS5Sw71jdoWZLezpDDAu+Glo4ntfqhMRvlv3Cx0T8XnoLqTq0Fqvn1DKR4epTHGebnf9cW33gg79mFbsaSq+O2L+afB08rHyQjMdOsgaIVqqbaK5v17GiSt+odV03kpUSSCnDAyCCuRDds3JEbiCiGjERBeGgB0+qOXBLtr8ibjpj9Du6Gw2YcoRf2XhimS20AGK8GpMUGw0jm5NaFnMvC1AqwtEwxXg29IbuikxkPXBZkfRhiBfMOu/efNeopQ0RbwRJecJepsWm7VLprLkhefWMOkuQExL//xgRUiz+cFEoc/8UZMy1p0VtMuSMU4Mzzqs=