backend:
  name: github
  repo: marzeelabs/coworkbuzz # Path to your Github repository
  branch: <% CURRENT_BRANCH %> # Branch to update (current branch dynamically set by Gulp)

media_folder: "/static/media/uploads" # Folder where user uploaded files should go
public_folder: "/media/uploads"
publish_mode: "editorial_workflow"

collections: # A list of collections the CMS should be able to edit

  - name: "settings"
    label: "Site settings"
    folder: "data"
    format: "yml"
    create: false
    editor:
      preview: false
    fields:
      - label: "[hidden]"
        name: "title"
        widget: "string"
        default: "Enter here to edit."
      - label: "Site name"
        name: "name"
        widget: "string"
      - label: "Tagline"
        name: "tagline"
        widget: "string"
      - label: "Short Description"
        name: "description"
        widget: "text"
      - label: "Ticket URL"
        name: "ticketurl"
        widget: "string"
        required: false
      - label: "E-mail"
        name: "email"
        widget: "string"
      - label: "Facebook"
        name: "facebook"
        widget: "string"
        required: false
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        required: false
      - label: "Map Embed Code"
        name: "map"
        widget: "string"
      - label: "Google Analytics tracking code"
        name: "ga"
        widget: "string"
        required: false
      - label: "Facebook Pixel ID"
        name: "fp"
        widget: "string"
        required: false
      - label: "Facebook Pixel Events"
        name: "fpe"
        widget: "list"
        required: false
        fields:
          - label: "Event"
            name: "event"
            widget: "string"

  - name: "intro"
    label: "Intro"
    folder: "content/homepage/intro"
    format: "yaml-frontmatter"
    create: false
    fields:
      - label: "[hidden]"
        name: "title"
        widget: "string"
        default: "Enter here to edit."
      - label: "When"
        name: "when"
        widget: "string"
      - label: "Where"
        name: "where"
        widget: "string"
      - label: "Banner image"
        name: "banner"
        widget: "image"

  - name: "about"
    label: "About"
    folder: "content/homepage/about"
    format: "yaml-frontmatter"
    create: false
    fields:
      - label: "[hidden]"
        name: "title"
        widget: "string"
        default: "Enter here to edit."
      - label: "Header Title"
        name: "header"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"

  - name: "register"
    label: "Register"
    folder: "content/homepage/register"
    format: "yaml-frontmatter"
    create: false
    fields:
      - label: "[hidden]"
        name: "title"
        widget: "string"
        default: "Enter here to edit."
      - label: "Header Title"
        name: "header"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Tickets"
        name: "tickets"
        widget: "list"
        required: false
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Price"
            name: "price"
            widget: "string"
          - label: "Option"
            name: "option"
            widget: "string"
          - label: "Button label"
            name: "btnlabel"
            widget: "string"
            default: "Get ticket!"
            required: false

  - name: "schedule"
    label: "Schedule"
    label_singular: "Day"
    folder: "content/homepage/schedule"
    format: "yaml-frontmatter"
    slug: "{{title}}"
    extension: "md"
    create: true
    fields:
      - label: "Day"
        name: "title"
        widget: "string"
      - label: "Header title"
        name: "name"
        widget: "string"
      - label: "Day"
        name: "day"
        widget: "string"
      - label: "Plan"
        name: "plan"
        widget: "list"
        required: false
        fields:
          - label: "Slot"
            name: "slot"
            widget: "string"
          - label: "Title"
            name: "name"
            widget: "string"
          - label: "Highlight"
            name: "break"
            widget: "boolean"
          - label: "Subtitles"
            name: "subs"
            widget: "list"
            fields:
              - label: "Label"
                name: "label"
                widget: "string"
      - label: "Description"
        name: "body"
        widget: "markdown"
        required: false

  - name: "partners"
    label: "Partners"
    folder: "content/homepage/partners"
    format: "yaml-frontmatter"
    create: false
    fields:
      - label: "[hidden]"
        name: "title"
        widget: "string"
        default: "Enter here to edit."
      - label: "Content"
        name: "body"
        widget: "markdown"
      - label: "Partners"
        name: "partners"
        widget: "list"
        fields:
          - label: "Label"
            name: "label"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
